train:
  num_epochs: 20
  batch_size: 64
  max_lr: 0.014
  decay_rate: 0.78
  weight_decay: 4.3e-05
  warmup_epochs: 3
  cosine_epochs: 17
  patience: 3
  checkpoints_dir: 'centralized_model/checkpoints/'
  logs_dir: 'centralized_model/logs/'
  plots_dir: 'centralized_model/plots/'

train_federated:
  num_rounds: 352
  num_clients: 100
  client_ratio: 0.1              # C
  num_steps_per_client: 4        # J
  num_classes_per_client: 100    # Nc
  rounds_per_scheduler_step: 4   # Number of rounds for a scheduler step (update)
  warmup_scheduler_steps: 13
  cosine_scheduler_steps: 75
  scale_grow_interval: 48        # Number of rounds for a scale grow
  validation_interval: 16        # Number of rounds for a validation
  batch_size: 64
  max_lr: 0.007
  decay_rate: 0.78
  weight_decay: 4.3e-05
  patience: 3                    # Number of VALIDATIONS to wait for an improvement before early stopping
  checkpoints_dir: 'federated_model/checkpoints/'
  logs_dir: 'federated_model/logs/'
  plots_dir: 'federated_model/plots/'